# Created with package:mono_repo v2.3.0
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
env:
  global: FORCE_TEST_EXIT=true
after_failure:
  - tool/report_failure.sh

jobs:
  include:
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `xvfb-run -s \"-screen 0 1024x768x24\" pub run test --preset travis test/runner/hybrid_test.dart`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `xvfb-run -s \"-screen 0 1024x768x24\" pub run test --preset travis test/runner/hybrid_test.dart`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `xvfb-run -s \"-screen 0 1024x768x24\" pub run test --preset travis test/runner/hybrid_test.dart`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `xvfb-run -s \"-screen 0 1024x768x24\" pub run test --preset travis test/runner/hybrid_test.dart`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `xvfb-run -s \"-screen 0 1024x768x24\" pub run test --preset travis test/runner/hybrid_test.dart`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test_api; TASKS: `pub run test --preset travis`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test_api"
      script: ./tool/travis.sh test

stages:
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
