# Created with package:mono_repo v2.3.0
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
env:
  global: FORCE_TEST_EXIT=true

jobs:
  include:
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `dart test/diagnose_exit.dart -fake1`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command_0
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `dart test/diagnose_exit.dart -fake2`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `dart test/diagnose_exit.dart -fake3`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command_2
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `dart test/diagnose_exit.dart -fake4`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command_3
    - stage: unit_test
      name: "SDK: dev; PKG: pkgs/test; TASKS: `dart test/diagnose_exit.dart -fake5`"
      dart: dev
      os: linux
      env: PKGS="pkgs/test"
      script: ./tool/travis.sh command_4

stages:
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
